app:
  image:
    repository: hieuletrong368/toge
    tag: 3
  network:
    http:
      ingress:
        host: toge.baloise.dev
  deployment:
    strategy:
      type: Recreate

dnsEndpoint:
  enabled: true
  recordTTL: 180