{{- if .Values.dnsEndpoint.enabled }}
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: {{ .Release.Name }}-dns-endpoint
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
    - dnsName: {{ .Values.app.network.http.ingress.host }}
      recordType: A
      recordTTL: {{ .Values.dnsEndpoint.recordTTL }}
      targets: [""]
{{- end }}