app:
  image:
    repository: hieu049087/ader
    tag: latest
  network:
    http:
      ingress:
        host: ader.baloise.dev
  deployment:
    strategy:
      type: Recreate
    configMaps:
      nginx-config:
        data:
          nginx.conf: |
            pid /tmp/nginx.pid;
            events {
                worker_connections 1024;
            }
            http {
                include /etc/nginx/mime.types;
                default_type application/octet-stream;
            
                sendfile on;
                keepalive_timeout 65;
            
                client_body_temp_path /tmp/client_temp;
                proxy_temp_path /tmp/proxy_temp;
                fastcgi_temp_path /tmp/fastcgi_temp;
                uwsgi_temp_path /tmp/uwsgi_temp;
                scgi_temp_path /tmp/scgi_temp;
            
                server {
                    listen 8080;
                    server_name localhost;
            
                    location / {
                        root /usr/share/nginx/html;
                        index index.html index.htm;
                        try_files $uri $uri/ /index.html;
                    }
                }
            }
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
      volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf