app:
  image:
    repository: hieu049087/ader
    tag: 1.0
  network:
    http:
      ingress:
        host: ader.baloise.dev
      volumeMounts:
        - mountPath: /etc/nginx/conf.d/
          name: nginx-dir
        - mountPath: /var/cache/nginx/client_temp
          name: nginx-empty
        - mountPath: /var/run/
          name: nginx-run

  deployment:
    strategy:
      type: Recreate